<?php
    function facetly_perm() {
        return array(
            'administer facetly search'
        );
    }

    function facetly_menu() {
        $items['admin/settings/facetly'] = array(
            'title' => 'Facetly Configuration',
            'description' => 'Facetly Configuration',
            'page arguments' => array(
                'facetly_admin_settings_form'
            ),
            'page callback' => 'drupal_get_form',
            'access arguments' => array(
                'administer facetly search'
            ),
            'type' => MENU_NORMAL_ITEM,
            'file' => 'facetly.admin.inc',
        );
        $items['admin/settings/facetly/consumer'] = array(
            'title' => 'Facetly Configuration',
            'description' => 'Facetly Configuration',
            'page arguments' => array(
                'facetly_admin_settings_form'
            ),
            'page callback' => 'drupal_get_form',
            'access arguments' => array(
                'administer facetly search'
            ),
            'type' => MENU_DEFAULT_LOCAL_TASK,
            'weight' => 0,
            'file' => 'facetly.admin.inc',
        );
        $items['admin/settings/facetly/field'] = array(
            'title' => 'Fields',
            'description' => 'Facetly Field Configuration',
            'page arguments' => array(
                'facetly_admin_field_settings_form'
            ),
            'page callback' => 'drupal_get_form',
            'access arguments' => array(
                'administer facetly search'
            ),
            'type' => MENU_LOCAL_TASK,
            'weight' => 1,
            'file' => 'facetly.admin.inc',
        );
        $items['admin/settings/facetly/reindex'] = array(
            'title' => 'Reindex',
            'description' => 'Facetly Reindex',
            'page arguments' => array(
                'facetly_admin_reindex_form'
            ),
            'page callback' => 'drupal_get_form',
            'access arguments' => array(
                'administer facetly search'
            ),
            'type' => MENU_LOCAL_TASK,
            'weight' => 3,
            'file' => 'facetly.admin.inc',
        );
        $items['admin/settings/facetly/template'] = array(
            'title' => 'Template',
            'description' => 'Facetly Template',
            'page arguments' => array(
                'facetly_admin_template_settings_form'
            ),
            'page callback' => 'drupal_get_form',
            'access arguments' => array(
                'administer facetly search'
            ),
            'type' => MENU_LOCAL_TASK,
            'weight' => 2,
            'file' => 'facetly.admin.inc',
        );
        $items['find'] = array(
            'title' => 'Search',
            'description' => 'Facetly Search Page',
            'page callback' => 'facetly_search_template_page',
            'access arguments' => array(
                'access content'
            ),
            'type' => MENU_CALLBACK,
            'file' => 'facetly.pages.inc',
        );
        $items['ajax/find/general/autocomplete'] = array(
            'title' => 'Facetly Json Autocomplete Search',
            'description' => 'Facetly Autocomplete Search ',
            'page callback' => 'facetly_autocomplete_search_page',
            'access arguments' => array(
                'access content'
            ),
            'type' => MENU_CALLBACK,
            'file' => 'facetly.pages.inc',
        );
        return $items;
    }

    function facetly_theme()
    {
        return array(
            'facetly_pager' => array(
                'arguments' => array(
                    'results' => NULL,
                    'limit' => NULL
                ),
                'file' => 'facetly.theme.inc',

            ),
            'facetly_search_form' => array(
                'arguments' => array(
                    'form' => NULL
                ),
                'file' => 'facetly.theme.inc',
            ),
            'facetly_item' => array(
                'arguments' => array(
                    'items' => NULL
                ),
                'file' => 'facetly.theme.inc',
            ),
            'facetly_item_list' => array(
                'arguments' => array(
                    'items' => NULL,
                    'title' => NULL,
                    'type' => NULL,
                    'attributes' => NULL
                ),
                'file' => 'facetly.theme.inc',
            )
        );
    }




    function facetly_add_js() {
        static $run;
        
        if (!$run) {
            global $base_url;
                    
            drupal_add_js(drupal_get_path('module', 'facetly') . '/js/jquery.address.js');
            drupal_add_js(drupal_get_path('module', 'facetly') . '/js/jquery.autocomplete.js');
            drupal_add_js(drupal_get_path('module', 'facetly') . '/js/facetly.js');
            
            $settings = array( 
                'facetly' => array(      
                'baseurl' => url("<front>"),
                'file' => url('find', array(
                    'absolute' => true,
                    'external' => true,
                    'query' => variable_get('facetly_extra_vars', ''),
                )),
                'server' => variable_get('facetly_server', ''),
                'key' => variable_get('facetly_key', ''),
                'limit' => variable_get('facetly_limit', 10)
            ));
            drupal_add_js($settings, 'setting');
            $run = TRUE;
        }
    }


    function facetly_block($op = 'list', $delta = 0, $edit = array()) {
        if ($op == 'list') {
            $blocks['facetly_search']  = array(
                'info' => t('Facetly: Search Form'),
                'weight' => 0
            );
            $blocks['facetly_faceted'] = array(
                'info' => t('Facetly: Filter Results'),
                'weight' => 0
            );
            return $blocks;
        } else if ($op == 'view') {
            module_load_include('inc','facetly','facetly.common');
            switch ($delta) {
                case 'facetly_search':
                    // Your module will need to define this function to render the block.
                    $block = array(
                        'subject' => t('Search'),
                        'content' => drupal_get_form('facetly_search_form', array(
                            'title' => FALSE
                        ))
                    );
                    break;
                case 'facetly_faceted':
                    // Your module will need to define this function to render the block.
                    $block = array(
                        'subject' => t('Filter Results'),
                        'content' => facetly_faceted_search()
                    );
                    break;
            }
            return $block;
        }
    }

    function facetly_nodeapi(&$node, $op) {
        switch ($op) {
            case 'insert':
            case 'update':
                $node_type = variable_get('facetly_node_type', array());
                if ($node->status == 1 && !empty($node_type[$node->type])) {
                    module_load_include('inc','facetly','facetly.common');
                    try {
                        facetly_reindex($node);
                    } catch (Exception $e) {
                        $message = $e->getMessage();
                        drupal_set_message(t($message), 'error', TRUE);
                    } 
                } else {
                    $facetly = facetly_api_init();
                    try {
                        $facetly->productDelete($node->nid);                        
                    } catch (Exception $e) {
                        $message = $e->getMessage();
                        drupal_set_message(t($message), 'error', TRUE);
                    }
                }
                break;
            case 'delete':
                $facetly = facetly_api_init();
                try {
                    $facetly->productDelete($node->nid);     
                } catch (Exception $e) {
                    $message = $e->getMessage();
                    drupal_set_message(t($message), 'error', TRUE);
                }                   
                break;
        }
    }

    function facetly_api_init($async = FALSE) {
        static $facetly;
        
        if (empty($facetly[$async])) {  
            module_load_include('php', 'facetly', 'facetly_api');
            $facetly[$async] = new facetly_api();
            $facetly[$async]->setServer(variable_get('facetly_server', ''), $async);
            $facetly[$async]->setConsumer(variable_get('facetly_key', ''), variable_get('facetly_secret', ''));
        }
        return $facetly[$async];
    }


